/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaMetadata = IDL.Record({
  'title' : IDL.Text,
  'size' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'fileType' : IDL.Text,
  'uploadDate' : IDL.Text,
});
export const MediaItem = IDL.Record({
  'id' : IDL.Text,
  'metadata' : MediaMetadata,
  'blob' : ExternalBlob,
});
export const DeviceStatus = IDL.Record({
  'batteryLevel' : IDL.Nat,
  'storageUsed' : IDL.Nat,
  'lastUpdate' : IDL.Text,
  'storageTotal' : IDL.Nat,
  'systemHealth' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addMediaItem' : IDL.Func([IDL.Text, ExternalBlob, MediaMetadata], [], []),
  'addNetwork' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'bulkAddMediaItems' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob, MediaMetadata))],
      [],
      [],
    ),
  'clearMediaLibrary' : IDL.Func([], [], []),
  'deleteMediaItem' : IDL.Func([IDL.Text], [], []),
  'deleteNetwork' : IDL.Func([IDL.Text], [], []),
  'getAllMediaItemsSortedByFileName' : IDL.Func(
      [],
      [IDL.Vec(MediaItem)],
      ['query'],
    ),
  'getDeviceStatus' : IDL.Func([], [IDL.Opt(DeviceStatus)], ['query']),
  'initiateLiveStream' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Variant({ 'success' : IDL.Text })],
      [],
    ),
  'searchMediaByTag' : IDL.Func([IDL.Text], [IDL.Vec(MediaItem)], ['query']),
  'setDeviceStatus' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'shareMediaItemWithDevice' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'success' : IDL.Text })],
      [],
    ),
  'updateMediaMetadata' : IDL.Func([IDL.Text, MediaMetadata], [], []),
  'updateNetwork' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaMetadata = IDL.Record({
    'title' : IDL.Text,
    'size' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'fileType' : IDL.Text,
    'uploadDate' : IDL.Text,
  });
  const MediaItem = IDL.Record({
    'id' : IDL.Text,
    'metadata' : MediaMetadata,
    'blob' : ExternalBlob,
  });
  const DeviceStatus = IDL.Record({
    'batteryLevel' : IDL.Nat,
    'storageUsed' : IDL.Nat,
    'lastUpdate' : IDL.Text,
    'storageTotal' : IDL.Nat,
    'systemHealth' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addMediaItem' : IDL.Func([IDL.Text, ExternalBlob, MediaMetadata], [], []),
    'addNetwork' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'bulkAddMediaItems' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, ExternalBlob, MediaMetadata))],
        [],
        [],
      ),
    'clearMediaLibrary' : IDL.Func([], [], []),
    'deleteMediaItem' : IDL.Func([IDL.Text], [], []),
    'deleteNetwork' : IDL.Func([IDL.Text], [], []),
    'getAllMediaItemsSortedByFileName' : IDL.Func(
        [],
        [IDL.Vec(MediaItem)],
        ['query'],
      ),
    'getDeviceStatus' : IDL.Func([], [IDL.Opt(DeviceStatus)], ['query']),
    'initiateLiveStream' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Variant({ 'success' : IDL.Text })],
        [],
      ),
    'searchMediaByTag' : IDL.Func([IDL.Text], [IDL.Vec(MediaItem)], ['query']),
    'setDeviceStatus' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'shareMediaItemWithDevice' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'success' : IDL.Text })],
        [],
      ),
    'updateMediaMetadata' : IDL.Func([IDL.Text, MediaMetadata], [], []),
    'updateNetwork' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };