/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DeviceStatus {
  'batteryLevel' : bigint,
  'storageUsed' : bigint,
  'lastUpdate' : string,
  'storageTotal' : bigint,
  'systemHealth' : string,
}
export type ExternalBlob = Uint8Array;
export interface MediaItem {
  'id' : string,
  'metadata' : MediaMetadata,
  'blob' : ExternalBlob,
}
export interface MediaMetadata {
  'title' : string,
  'size' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'fileName' : string,
  'fileType' : string,
  'uploadDate' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addMediaItem' : ActorMethod<
    [string, ExternalBlob, MediaMetadata],
    undefined
  >,
  'addNetwork' : ActorMethod<[string, string, string, string], undefined>,
  'bulkAddMediaItems' : ActorMethod<
    [Array<[string, ExternalBlob, MediaMetadata]>],
    undefined
  >,
  'clearMediaLibrary' : ActorMethod<[], undefined>,
  'deleteMediaItem' : ActorMethod<[string], undefined>,
  'deleteNetwork' : ActorMethod<[string], undefined>,
  'getAllMediaItemsSortedByFileName' : ActorMethod<[], Array<MediaItem>>,
  'getDeviceStatus' : ActorMethod<[], [] | [DeviceStatus]>,
  'initiateLiveStream' : ActorMethod<
    [string, string, Array<string>],
    { 'success' : string }
  >,
  'searchMediaByTag' : ActorMethod<[string], Array<MediaItem>>,
  'setDeviceStatus' : ActorMethod<
    [bigint, bigint, bigint, string, string],
    undefined
  >,
  'shareMediaItemWithDevice' : ActorMethod<
    [string, string],
    { 'success' : string }
  >,
  'updateMediaMetadata' : ActorMethod<[string, MediaMetadata], undefined>,
  'updateNetwork' : ActorMethod<[string, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];